ALTER TABLE ss_spot_review
ADD COLUMN IF NOT EXISTS created DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS  modified DATE;

ALTER TABLE ss_spot_review
ADD COLUMN IF NOT EXISTS created DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS modified DATE;