ALTER TABLE ss_event
ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ss_event
ADD COLUMN created_by VARCHAR(255);

ALTER TABLE ss_event
ADD COLUMN modified TIMESTAMP;

ALTER TABLE ss_event
ADD COLUMN modified_by VARCHAR(255);
